HW13 is completed
natalya-revtova/go-practice pull request #14
Opened 2023-08-30 09:24 UTC by natalya-revtova

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-30 09:38 UTC, natalya-revtova commented on hw12_13_14_15_calendar/internal/calendar/calendar.go
> +			"request_id", middleware.GetReqID(ctx),
Не очень поняла, как в итоге работать с request_id... В middleware мы помещяем его в контекст, и неужели его вот так из кнтекста всё время доставать нужно?

2023-08-31 01:29 UTC, dshemin requested changes

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/api/calendar/calendar.proto
> +    rpc CreateEvent (CreateEventRequest) returns (google.protobuf.Empty) {}
Важно:

Нам было бы неплохо вернуть хотя бы ID созданного события. Иначе как клиент потом может с ним работать?

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/api/calendar/calendar.proto
> +message CreateEventResponse {}
Важно:

Видимо уже не нужные сообщения, стоит удалить.

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/configs/config.toml
> +type = "in-memory"
Важно:

Думаю чтоит вернуть обратно sql

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/internal/calendar/calendar.go
> +		c.log.Error("Can not add event to storage",
Важно:

С ошибками принято делать две вещи: обрабатывать или возвращать. При этом делать и то, и то - не рекомендуется. Логирование - это тоже обработка.

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/internal/calendar/calendar.go
> +			"request_id", middleware.GetReqID(ctx),
В целом да.

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/internal/models/event.go
> +func (e *Event) UpdateForStorage() *Event {
Важно:

Это действие специфично для одной конкретной операции, не стоит её выносит за пределы этой операции.

2023-08-31 01:29 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/events.go
> +		Title:            event.GetTitle(),
Критично:

Тут мы не заполняем ID, а для обновления это нам нужно.

2023-08-31 11:36 UTC, natalya-revtova commented on hw12_13_14_15_calendar/internal/calendar/calendar.go
> +		c.log.Error("Can not add event to storage",
То есть лучше возвращать все ошибки на rest уровень и там их логировать?

2023-08-31 15:14 UTC, natalya-revtova commented on hw12_13_14_15_calendar/api/calendar/calendar.proto
> +    rpc CreateEvent (CreateEventRequest) returns (google.protobuf.Empty) {}
done

2023-08-31 15:14 UTC, natalya-revtova commented on hw12_13_14_15_calendar/api/calendar/calendar.proto
> +message CreateEventResponse {}
done

2023-08-31 15:14 UTC, natalya-revtova commented on hw12_13_14_15_calendar/configs/config.toml
> +type = "in-memory"
done

2023-08-31 15:14 UTC, natalya-revtova commented on hw12_13_14_15_calendar/internal/calendar/calendar.go
> +		c.log.Error("Can not add event to storage",
done

2023-08-31 15:14 UTC, natalya-revtova commented on hw12_13_14_15_calendar/internal/models/event.go
> +func (e *Event) UpdateForStorage() *Event {
done

2023-08-31 15:14 UTC, natalya-revtova commented on hw12_13_14_15_calendar/internal/server/grpc/events.go
> +		Title:            event.GetTitle(),
done

2023-09-01 01:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/calendar/calendar.go
> +		c.log.Error("Can not add event to storage",
Да, именно так.

2023-09-01 01:30 UTC, dshemin approved these changes

2023-09-01 05:13 UTC, merged